server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: memory-client

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memory_api
    username: root
    password: Dw990831

memory-api:
  client:
    access-key: memory
    secret-key: 12345678
